name: Setup Chrome Remote Desktop on Windows

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  setup-rdp:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Google Chrome
        run: |
          powershell -Command "Invoke-WebRequest -Uri 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile 'chrome_installer.exe'"
          powershell -Command "Start-Process -FilePath './chrome_installer.exe' -ArgumentList '/silent', '/install' -Wait"

      - name: Install Chrome Remote Desktop
        run: |
          powershell -Command "Invoke-WebRequest -Uri 'https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi'"
          powershell -Command "Start-Process -FilePath './chromeremotedesktophost.msi' -ArgumentList '/quiet', '/norestart' -Wait"

      - name: Configure Chrome Remote Desktop
        env:
          CHROME_REMOTE_DESKTOP_PIN: "9016"
        run: |
          powershell -Command "Set-Content -Path 'C:\\chromeremotedesktopconfig.txt' -Value 'PIN=${{ env.CHROME_REMOTE_DESKTOP_PIN }}'"
          powershell -Command "Start-Process -FilePath 'C:\\Program Files (x86)\\Google\\Chrome Remote Desktop\\remoting_start_host.exe' -ArgumentList '--pin=${{ env.CHROME_REMOTE_DESKTOP_PIN }}' -Wait"

      - name: Output Access Code
        run: |
          echo "Access code for remote desktop is: ${{ env.CHROME_REMOTE_DESKTOP_PIN }}"
